export enum salaryReturnFieldMatch {
    'Lang_21' = '试用期',
    'Lang_22' = '转正后',
    'Lang_23' = '试用期工资',
    'Lang_24' = '转正后工资',
    'Lang_25' = 'totalBaseSalary',
    'Lang_26' = '岗位补贴',
    'Lang_27' = '加班费',
    'Lang_28' = '加班补助',
    'Lang_29' = '总补贴',
    'Lang_210' = '小孩补贴',
    'Lang_211' = '油费补贴',
    'Lang_212' = 'totalReward',
    'Lang_213' = '绩效奖金',
    'Lang_214' = '纪律奖',
    'Lang_215' = '其他',
    'Lang_216' = '福利',
    'Lang_217' = '工龄补贴',
    'Lang_218' = '扣款',
    'Lang_219' = '社保',
    'Lang_220' = '医保',
    'Lang_221' = '失业保',
    'Lang_222' = '个人所得税',
    'Lang_223' = '工会费',
}
